### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by cdaniel** [cdaniel/wardleymapstool#70]
[2015-12-14 11:58:19.664] [INFO] console - Mon Dec 14 2015 11:58:19 GMT-0500 (EST): Node server stopped.
/var/lib/openshift/534ea1d95004466102000286/app-root/runtime/repo/node_modules/q/q.js:155
                throw e;
                      ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
    at ServerResponse.header (/var/lib/openshift/534ea1d95004466102000286/app-root/runtime/repo/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/var/lib/openshift/534ea1d95004466102000286/app-root/runtime/repo/node_modules/express/lib/response.js:163:12)
    at ServerResponse.json (/var/lib/openshift/534ea1d95004466102000286/app-root/runtime/repo/node_modules/express/lib/response.js:249:15)
    at ServerResponse.send (/var/lib/openshift/534ea1d95004466102000286/app-root/runtime/repo/node_modules/express/lib/response.js:151:21)
    at /var/lib/openshift/534ea1d95004466102000286/app-root/runtime/repo/server/router/apirouter.js:77:25
    at /var/lib/openshift/534ea1d95004466102000286/app-root/runtime/repo/server/maps.js:684:25
From previous event:
    at Object.getMap (/var/lib/openshift/534ea1d95004466102000286/app-root/runtime/repo/server/maps.js:682:23)
    at /var/lib/openshift/534ea1d95004466102000286/app-root/runtime/repo/server/router/apirouter.js:69:8
    at Layer.handle [as handle_request] (/var/lib/openshift/534ea1d95004466102000286/app-root/runtime/repo/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/lib/openshift/534ea1d95004466102000286/app-root/runtime/repo/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/var/lib/openshift/534ea1d95004466102000286/app-root/runtime/repo/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/lib/openshift/534ea1d95004466102000286/app-root/runtime/repo/node_modules/express/lib/router/layer.js:95:5)
    at /var/lib/openshift/534ea1d95004466102000286/app-root/runtime/repo/node_modules/express/lib/router/index.js:277:22
DEBUG: Program node server/server.js exited with code 8
DEBUG: Starting child process with 'node server/server.js'

**Comment by cdaniel** [comment]
fixed
